version: "3.8"

networks:
    network:
    
services:
    kitchensink:
        image: superuserz/kitchesink-backend:latest
        ports:
                - 8080:8080
        environment:
                - server.port=8080
        networks:
                - network